### ISSUE TITLE
Set up Google Cloud Platform Postgres as a source in Airbyte

### ISSUE THREAD

**Issue by RoseateSpoonbill** [airbytehq/write-for-the-community#157]
How can I connect to a GCP Postgres database as a Airbyte source?
1. What set up steps do I need to take?
2. What values do I use for the new Airbyte source configuration?  (and where do I get them?)

I specifically need this information for these 
1. Airbyte Deployment locations
   1. Local Airbyte deployment
   1. GCP Compute Engine
   1. On Kubernetes
1. Methods of authorizing to GCP Postgres
   1. Cloud SQL Auth proxy
   1. Self-managed SSL/TLS certificates
   1. Authorized networks

It would be great if https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/postgres.md could be updated with this information 

### Stretch
For the tutorial to be most helpful for the widest audience, it would probably be best if the tutorial showed this information for all of the other places Airbyte can be deployed to
1. Airbyte Cloud
1. On AWS (EC2)
1. On AWS ECS
1. On Azure(VM)
1. On Plural
1. On Oracle Cloud Infrastructure VM
1. On DigitalOcean (Droplet)

**Comment by RoseateSpoonbill** [comment]
I ended up not being able to figure out how to do this locally.  

⚠️ THIS DOES NOT WORK ⚠️ 

This was as far as I got but I couldn't figure out either the right host name or what I was doing wrong in the addition to docker-compose.yaml
1. In your `airbyte` repository, open your `docker-compose.yaml` file and add this at the bottom of the `services` top level section
    ```
      proxy:
        container_name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.0
        volumes:
          - ..\{{FULL_PATH_TO_SERVICE_ACCOUNT_JSON_FILE}}:/config
        ports:
          - 127.0.0.1:5436:5436 
        command: "/cloud_sql_proxy -instances={{INSTANCE_CONNECTION_NAME}}=tcp:5436 -credential_file=/config/{{SERVICE_ACCOUNT_JSON_FILE_NAME}}"
    ```
1. Follow the instructions in the `Start Airbyte` section above
1. Once Airbyte loads, in the lefthand menu click `Sources`
1. Click `+ add new source`
   1. Choose `Postgres` from the dropdown menu
   1. Host: :question:
   1. Port: `5436`
   1. Fill in other fields
   1. Replication Method: `Standard`
   1. SSH Tunnel Method: `No Tunnel`
   1. Click `Set up source`

---

⚠️ This also did not work ⚠️ 
Run the Cloud SQL Auth proxy in a Docker container (per https://cloud.google.com/sql/docs/postgres/connect-admin-proxy#connecting-docker) as I couldn't figure out
1. Which Airbyte Docker container needed to connect to the Proxy Docker container
2. How to connect them
